/**
 * Visual and layout tokens — single source of truth for UI styling (see SPEC.md style guidelines).
 */
export const THEME = {
  color: {
    backgroundApp: "#f8fafc",
    surface: "#ffffff",
    borderDefault: "#e5e7eb",
    borderMuted: "#d1d5db",
    textPrimary: "#111827",
    textSecondary: "#4b5563",
    textBody: "#374151",
    textMuted: "#6b7280",
    textStrong: "#1f2937",
    primaryButton: "#0284c7",
    primaryAction: "#0ea5e9",
    onPrimary: "#ffffff",
    controlDisabled: "#94a3b8",
    destructive: "#dc2626",
    messageUserBg: "#e0f2fe",
    messageAssistantBg: "#f3f4f6",
    sheetHandle: "#d1d5db",
    offlineText: "#92400e",
    offlineBg: "#fef3c7",
    offlineBorder: "#fcd34d",
    errorSurface: "#fef2f2",
    errorBorder: "#fecaca",
    errorText: "#991b1b",
    dimmingOverlay: "rgba(17, 24, 39, 0.35)",
  },
  font: {
    size2xs: 12,
    sizeXs: 13,
    sizeSm: 14,
    sizeMd: 15,
    sizeBody: 16,
    sizeLg: 17,
    sizeTitle: 18,
    sizeHero: 28,
    lineHeightMessage: 20,
    lineHeightBody: 22,
    weightSemibold: "600" as const,
    weightBold: "700" as const,
  },
  space: {
    xs: 4,
    sm: 6,
    md: 8,
    lg: 10,
    xl: 12,
    xxl: 14,
    xxxl: 16,
    inputMinHeight: 42,
    inputMaxHeight: 120,
    sheetHandleWidth: 48,
    sheetHandleHeight: 4,
    hitSlop: 12,
  },
  radius: {
    sm: 8,
    md: 10,
    lg: 12,
    sheetTop: 16,
    pill: 999,
  },
  layout: {
    recipeEditorChatBottomInset: 260,
    messageUserMaxWidth: "85%" as const,
    messageAssistantMaxWidth: "95%" as const,
    trashIconSize: 22,
  },
  metrics: {
    expandedHeightRatio: 0.72,
    collapseSwipeThreshold: 48,
    collapsedInputBottomPadding: 12,
  },
} as const;
